// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContextRedarbor))]
    [Migration("20260221211319_TableUpdateSomeColumns")]
    partial class TableUpdateSomeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.EmployeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Employ");

                    b.ToTable("Employee", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.EmployeEntity", b =>
                {
                    b.OwnsOne("Domain.CompanyId", "CompanyId", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Email", "Email", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Fax", "Fax", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Name", "Name", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Password", "Password", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.PortalId", "PortalId", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.RoleId", "RoleId", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.StatusId", "StatusId", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Telephone", "Telephone", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.OwnsOne("Domain.Username", "Username", b1 =>
                        {
                            b1.Property<int>("EmployeEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.HasKey("EmployeEntityId");

                            b1.ToTable("Employee", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EmployeEntityId");
                        });

                    b.Navigation("CompanyId")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Fax")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("PortalId")
                        .IsRequired();

                    b.Navigation("RoleId")
                        .IsRequired();

                    b.Navigation("StatusId")
                        .IsRequired();

                    b.Navigation("Telephone")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
